---
title: "HW5"
author: "Nathalie Fadel"
date: "11/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(purrr)
library(viridis)
set.seed(1)
```

#Problem 1
```{r}
names = list.files("./data", full.names = TRUE)

df = names %>%
  map(read_csv)

for (i in 1:20)
  if (i <= 10) {
    df[[i]] = df[[i]] %>% 
      mutate(arm = "Control", study_id = i)
  } else if (i > 10) {
    df[[i]] = df[[i]] %>% 
      mutate(arm = "Experimental", study_id = i - 10)
  }

df = bind_rows(df) %>%
  gather(key = "week", week_1:week_8, value = "value") %>%
  mutate(week = as.numeric(str_extract(week, "\\d"))) 
data = df

data %>%
  mutate(study_id = as.character(study_id)) %>%
  group_by(arm, study_id) %>%
  ggplot(aes(x = week, y = value, color = arm, type = study_id)) +
  geom_line() +
  labs(y = "value", caption = "response per subject over time")
```

#Problem 2
```{r}
murder_data = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

murder_data = murder_data %>%
  unite("city_state", c("city", "state"), sep = ",", remove = TRUE)

unsolved_cases =
  murder_data %>%
  filter(disposition %in% c("Open/No arrest", "Closed without arrest")) %>%
  group_by(city_state) %>%
  summarize(unsolved_cases = n())

total_murders =
  murder_data %>%
  group_by(city_state) %>%
  summarize(total = n())

total_cases = 
  left_join(unsolved_cases, total_murders, by = "city_state")


p_unsolved = function(df) {
  cl_unsolved = prop.test(df$unsolved_cases, df$total)
  
  broom::tidy(cl_unsolved) %>% 
    select(estimate, conf.low, conf.high)
    }

total_cases %>%
  filter(city_state == "Baltimore,MD") %>%
  p_unsolved %>%
  knitr::kable() 

city_nest = nest(total_cases, unsolved_cases:total)

unsolved_cl = city_nest %>% 
  mutate(p_unsolved = map(data, p_unsolved)) %>% 
  unnest() %>%
  rename(lb = conf.low, ub = conf.high)

unsolved_cl %>%
 mutate(city_state = forcats::fct_reorder(city_state, estimate)) %>%
ggplot(aes(x = city_state, y = estimate)) +
  geom_col() +
  geom_errorbar(aes(ymin = lb, ymax = ub)) +
  theme(axis.text.x = element_text(angle=90, hjust=1))
    
```